name:                ga-lz77
version:             0.1.0.0
github:              "reubensammut /ga-lz77"
license:             BSD3
author:              "Reuben Sammut"
maintainer:          "reubensammut@gmail.com"
copyright:           "2019 Reuben Sammut"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/reubensammut/ga-lz77#readme>

dependencies:
- base >= 4.7 && < 5
- natural-numbers

library:
  source-dirs: src

executables:
  ga-lz77-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ga-lz77

tests:
  ga-lz77-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ga-lz77
